version: '3'
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    hostname: "traefik"
    restart: always
    environment:
      - "DNSIMPLE_OAUTH_TOKEN=${DNSIMPLE_OAUTH_TOKEN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/traefik/traefik.yaml:/traefik.yaml
      - ./config/traefik/users.txt:/users.txt
      - ./config/traefik/acme.json:/acme.json
      - ./config/traefik/dynamic:/dynamic
      - /run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    dns:
      - 1.1.1.1
    depends_on:
      - jaeger
  consul:
    image: consul:1.9.3
    container_name: "consul"
    hostname: "consul"
    restart: always
    networks:
      - traefik
      - internal
    dns:
      - 1.1.1.1
    volumes:
      - ./config/consul/server.hcl:/etc/consul/server.hcl
      - ./config/consul/client.hcl:/etc/consul/client.hcl
      - ./data/consul:/opt/consul
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger"
    hostname: "jaeger"
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - internal
      - traefik
    dns:
      - 1.1.1.1
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'git.lab.tiffany-family.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.lab.tiffany-family.net'
        nginx['ssl_session_timeout'] = "5m"
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['backup_archive_permissions'] = 0644
        gitlab_rails['backup_keep_time'] = 1468800
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'region' => 'us-east-1',
          'aws_access_key_id' => "${S3_ACCESS_KEY}",
          'aws_secret_access_key' => "${S3_SECRET_KEY}",
          'host' => "${S3_ENDPOINT}"
        }
        gitlab_rails['backup_upload_remote_directory'] = 'jupiter-gitlab-backup'
    ports:
      - "8022:22"
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`git.lab.tiffany-family.net`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=letsencrypt
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.middlewares=simpleAuth
    volumes:
      - './config/gitlab:/etc/gitlab'
      - './logs/gitlab:/var/log/gitlab'
      - './data/gitlab:/var/opt/gitlab'

networks:
  traefik:
    external: true
  internal: 
    external: false
