entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
api:
  dashboard: true
http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'ryan:$apr1$uSzn5oSf$NrjPhjAmYzSNrRHxfZU5c/'
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      email: ryantiffany@fastmail.com
      storage: acme.json
      dnsChallenge:
        provider: dnsimple
        delayBeforeCheck: 0
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'
providers:
  file:
    directory: /dynamic
    watch: true
  docker:
    exposedByDefault: false
    network: traefik
log:
  level: DEBUG
  filePath: /var/log/traefik.log
tracing:
  serviceName: traefik
  jaeger:
    collector:
        endpoint: http://192.168.4.110:14268/api/traces?format=jaeger.thrift
